
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#开发环境配置
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8
   username: root
   password: Yxq12345!
   driver-class-name: com.mysql.cj.jdbc.Driver




